version: 0.0
os: linux
files:
  - source: /
    destination: /opt/app/releases/app
permissions:
  - object: /opt/app/release/app
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: ec2-user
